### ISSUE TITLE
Error to load savedModel?

### ISSUE THREAD

**Issue by msarfrazcss** [kalaspuffar/rcnn-model-test#1]
Hi @kalaspuffar thanks for your post,

I have downloaded your java code from the link: https://github.com/kalaspuffar/rcnn-model-test
and i have placed a protobuf file (.pb) into waldo directory.

VM arguments:   -Djava.library.path=./waldo_model

**Directory structure is:**
![waldo](https://user-images.githubusercontent.com/43664119/49437513-b15a7d80-f7e1-11e8-91be-6cec218ca956.png)

When i run my code it gives error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.tensorflow.SavedModelBundle.load(Ljava/lang/String;[Ljava/lang/String;[B)Lorg/tensorflow/SavedModelBundle;
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at org.ea.waldo.RunInference.main(RunInference.java:54)

Error comes at line:
**SavedModelBundle smb = SavedModelBundle.load("./waldo_model/saved_model", "serve");**
Can you tell me please where i am going wrong?

**Comment by kalaspuffar** [comment]
Hi @msarfrazcss 

If you look at the documentation you will see that some files are missing. For instance, you don't have the actual variables of the model, the actual data.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md

Hope this helps.

Best regards
Daniel
