### ISSUE TITLE
anaconda prompt

### ISSUE THREAD

**Issue by Ibmaria** [kalaspuffar/rcnn-model-test#2]
hello @kalaspuffar 
thanks for your post , i have a question . I train in the cloud. Should I run the command in anaconda prompt or google cloud .
ml-engine jobs submit training object_detection_`date +%s` \
    --runtime-version 1.7 \
    --job-dir=gs://mloutput/workdata/model/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --region us-central1 \
    --config /home/woden/github/rcnn-model-test/gcp_train.yaml \
    -- \
    --train_dir=gs://mloutput/workdata/model/train \
    --pipeline_config_path=gs://mloutput/workdata/model/mymodel.config
Thanks in advance

**Comment by kalaspuffar** [comment]
Hi @Ibmaria 

This command is targeted against Google cloud.

I think the information in this video might help.

https://youtu.be/3U6kzYfrpe8

Best regards
Daniel

**Comment by Ibmaria** [comment]
hi @kalaspuffar 
Thanks you 
Best regards
Ibra
