### ISSUE TITLE
google cloud

### ISSUE THREAD

**Issue by Ibmaria** [kalaspuffar/rcnn-model-test#3]
hello @kalaspuffar 
I submit my training job in the cloud but always i got :
jobId: object_detection 
state: queued 
After a few minutes the job failed .
How do deal with it .Thanks in advance 
regards 
ibra

**Comment by kalaspuffar** [comment]
Hi @Ibmaria 

The standard gpus might not be able to solve your problem you might need to scale up.

Or the model might have a problem with parallel calculation. Try running with a single unit first.

Hope this helps

Best regards
Daniel

**Comment by Ibmaria** [comment]
@kalaspuffar 
Thanks
